### PR TITLE
Add convention for PersistenceDiagram

### PR DESCRIPTION
**Pull request by mtsch**
This PR adds a convention for `scitype(::PersistenceDiagram, ::MLJ) = PersistenceDiagram`.

I also added entries into the docs. Let me know if I missed anything.

cc: @ablaom

### CODE REVIEW

**Review by ablaom — CHANGES_REQUESTED** [review]
@mtsch This looks great. One last thing. For better performance when computing the scitype of arrays with `PersistenceDiagram` as eltype, you should implement `Scitype`. You can just add the following

```julia
ST.Scitype(::Type{<:PersistenceDiagram},        ::MLJ) = PersistenceDiagram
```
 
to [this code](https://github.com/alan-turing-institute/MLJScientificTypes.jl/blob/4b5f97182d288b99afaf610b9d6d2436ae5098d6/src/convention/scitype.jl#L42) .

For more on this, query `?ScientificTypes.Scitypee`.

**Comment by ablaom** [comment]
And can you switch the PR target from `master` to `dev`

 https://github.com/alan-turing-institute/MLJ.jl/blob/master/CONTRIBUTING.md .

**Comment by mtsch** [comment]
Just a quick question. If I understand this correctly, `Scitype` needs to be overloaded for the case when you have an `Array` of non-concrete types. `PersistenceDiagram` has no type parameters. Is overloading `Scitype` still necessary in this case?

**Comment by ablaom** [comment]
Yes, it is still necessary. 

Otherwise `scitype(v)` will compute the union of all the scitypes of the elements of `v`, whenever `eltype(v) <: PersistentDiagram`. This is a long story.

**Comment by mtsch** [comment]
OK, thanks for the clarification. I added the definition.

**Pull request merged**
